import test from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { evaluateStructuredPrediction as evaluate } from '../hypothesis/evaluate.js';

// Every real module uses a private schema, including sequences and event output.
const dsn = process.env.OCA_TEST_DATABASE_URL || 'postgres://localhost/oneiro';
const schema = 'behavior_test_' + randomBytes(6).toString('hex');
const admin = new pg.Pool({ connectionString: dsn });
await admin.query('CREATE SCHEMA ' + schema);
const isolated = new URL(dsn); isolated.searchParams.set('options', '-c search_path=' + schema + ',public');
process.env.DATABASE_URL = isolated.toString();
const { pool } = await import('../event-bus.js');
test.after(async () => { await pool.end(); await admin.query('DROP SCHEMA ' + schema + ' CASCADE'); await admin.end(); });
for (const table of ['hypotheses', 'calibration_log', 'prediction_ledger', 'cognitive_events', 'hypothesis_graveyard',
  'emotional_states', 'benchmark_history', 'episodic_memory', 'creative_artifacts', 'causal_experiments', 'counterfactuals', 'prospective_memory']) {
  await pool.query(`CREATE TABLE ${table} (LIKE public.${table} INCLUDING DEFAULTS INCLUDING CONSTRAINTS)`);
  await pool.query(`ALTER TABLE ${table} ALTER COLUMN id DROP DEFAULT`);
  await pool.query(`ALTER TABLE ${table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`);
}
await pool.query(await readFile(new URL('../migrations/053_behavioral_integrity.sql', import.meta.url), 'utf8'));
const emotion = await import('../emotion/engine.js');
const hypothesis = await import('../hypothesis/engine.js');
const crm = await import('../evaluation/chinese-room-meter.js');
const anti = await import('../evaluation/anti-decay.js');
const baseline = emotion.snapshotState();

const expectation = { metric: 'battery_pct', operator: 'gte', value: 50 };
test('missing sensors and confident prose remain unknown, not false or true', () => {
  for (const data of [{}, { battery_pct: 'unknown' }, { battery_pct: NaN }, { _description: 'battery_pct=90' }]) {
    assert.equal(evaluate(expectation, data).verifiable, false);
    assert.equal(evaluate(expectation, data).confirmed, null);
  }
});
test('malformed expected numeric values and nonnumeric observations cannot refute a belief', () => {
  for (const [rule, data] of [[expectation, {battery_pct:'plenty'}], [{...expectation,value:'high'}, {battery_pct:90}],
    [{...expectation,operator:'between',min:90,max:10}, {battery_pct:50}], [{metric:'x'}, {x:1}]]) {
    assert.equal(evaluate(rule,data).verifiable,false);
  }
});
test('real zero, false and measured contradiction stay distinguishable', () => {
  assert.equal(evaluate({metric:'charging',value:false},{charging:false}).confirmed,true);
  assert.equal(evaluate({metric:'battery_pct',value:0},{battery_pct:0}).confirmed,true);
  assert.equal(evaluate(expectation,{battery_pct:20}).confirmed,false);
  assert.equal(evaluate(expectation,{battery_pct:90}).confirmed,true);
});

function reset(now) { emotion.restoreState({...structuredClone(baseline),savedAt:now}); }
test('ten minutes of idle is cadence-invariant and cannot manufacture satisfaction', t => {
  let now = 0; t.mock.method(Date,'now',()=>now);
  function run(step) {
    now=0; reset(now);
    for (let sec=0;sec<=600;sec+=step) { now=sec*1000; emotion.processIdle(sec/60); emotion.processInteroception(1,.2,.1,0); }
    return emotion.default.getState();
  }
  const fast=run(5),slow=run(60);
  for (const k of ['P','A','D','C','N']) assert.ok(Math.abs(fast._padcn[k]-slow._padcn[k])<1e-10,k);
  for (const k of ['novelty_seek','social_bond','competence','curiosity']) assert.ok(Math.abs(fast._drives[k].level-slow._drives[k].level)<1e-10,k);
  assert.equal(fast.satisfaction,0); assert.equal(fast._self_model.self_efficacy,baseline.selfModel.self_efficacy);
  assert.equal(fast._drives.competence.level,baseline.drives.competence.level);
});
test('zero/invalid magnitude, unchanged readings and returned state cannot mutate competence', () => {
  reset(Date.now());
  emotion.processSuccess(0); emotion.processSuccess('creative'); emotion.processInformationGain(0);
  emotion.processInteroception({energy:.2});
  for(let i=0;i<200;i++) emotion.processInteroception(1,.2,.1,0);
  const s=emotion.default.getState(); s._drives.competence.level=0;
  assert.equal(emotion.default.getState()._drives.competence.level,baseline.drives.competence.level);
  assert.ok(Object.values(emotion.default.getState()._padcn).every(Number.isFinite));
});
test('success and failure change affect differently; novelty alone cannot satiate competence', () => {
  reset(Date.now()); emotion.processSurprise(.8,'test');
  assert.equal(emotion.default.getState()._drives.competence.level,baseline.drives.competence.level);
  emotion.processInteraction(.8);
  assert.equal(emotion.default.getState()._self_model.self_efficacy,baseline.selfModel.self_efficacy,'positive social input is not measured competence');
  reset(Date.now()); emotion.processSuccess(.8); const success=emotion.default.getState();
  reset(Date.now()); emotion.processFailure(10,.8); const failure=emotion.default.getState();
  assert.ok(success.valence>failure.valence); assert.ok(failure.frustration>success.frustration);
  assert.ok(success._self_model.self_efficacy>failure._self_model.self_efficacy);
});
test('the complete affect state is durably restored without replay or satisfaction drift', async t => {
  let now=10000; t.mock.method(Date,'now',()=>now); reset(now);
  emotion.processFailure(10,.8); emotion.processIdle(7); await emotion.update();
  const before=emotion.snapshotState();
  reset(now); await emotion.restore(); const after=emotion.snapshotState();
  for(const k of ['padcn','channels','drives','selfModel','personality','failureStreak','lastIdleMinutes']) assert.deepEqual(after[k],before[k],k);
  now+=3600000; await emotion.restore();
  const cooled=emotion.snapshotState();
  assert.ok(Math.abs(cooled.padcn.P-cooled.personality.baseline_positive_affect)<Math.abs(before.padcn.P-before.personality.baseline_positive_affect));
  assert.deepEqual(cooled.drives,before.drives,'offline time does not satisfy wants');
});

async function prediction(expected=expectation) {
  return (await pool.query(`INSERT INTO hypotheses (domain,claim,prediction,confidence,status,source_data,created_at)
    VALUES ('fixture','Battery will be above threshold','battery >= 50',.7,'pending',$1,NOW()-INTERVAL '1 minute') RETURNING id`,
    [JSON.stringify({evaluation:expected})])).rows[0].id;
}
test('unobserved hypothesis is terminal unknown with no calibration or invented surprise', async () => {
  const id=await prediction(); const r=await hypothesis.test(id,{description:'Definitely battery >= 50',observed:{battery_pct:'unknown'}});
  assert.equal(r.status,'expired'); assert.equal(r.confirmed,null); assert.equal(r.surprise,null);
  const row=(await pool.query('SELECT * FROM hypotheses WHERE id=$1',[id])).rows[0];
  assert.equal(row.confidence_delta,0);
  assert.equal((await pool.query('SELECT COUNT(*)::int AS n FROM calibration_log')).rows[0].n,0);
  const ledger=(await pool.query('SELECT * FROM prediction_ledger WHERE hypothesis_id=$1',[id])).rows[0];
  assert.equal(ledger.prediction_error,null); assert.equal(ledger.status,'unverifiable');
});
test('concurrent observations calibrate once and conflicting replay cannot revise the outcome', async () => {
  const id=await prediction();
  const runs=await Promise.all([hypothesis.test(id,{observed:{battery_pct:90}}),hypothesis.test(id,{observed:{battery_pct:90}})]);
  assert.equal(runs.filter(r=>r.duplicate).length,1);
  assert.equal((await pool.query('SELECT COUNT(*)::int AS n FROM calibration_log')).rows[0].n,1);
  assert.equal((await pool.query('SELECT COUNT(*)::int AS n FROM prediction_ledger WHERE hypothesis_id=$1',[id])).rows[0].n,1);
  const replay=await hypothesis.test(id,{observed:{battery_pct:10}}); assert.equal(replay.duplicate,true);
  assert.equal((await pool.query('SELECT status FROM hypotheses WHERE id=$1',[id])).rows[0].status,'confirmed');
});
test('a falsified prediction is archived without rewording itself into another attempt', async () => {
  const id=await prediction(); const r=await hypothesis.test(id,{observed:{battery_pct:10}});
  assert.equal(r.status,'refuted'); assert.equal(r.revision.replacementHypothesisId,null); assert.equal(r.revision.error,undefined);
});
test('activity volume cannot fill missing capability evidence', async () => {
  const result=await crm.compute(); assert.equal(result.composite,null); assert.equal(result.evidence_coverage,0);
  assert.equal(result.components.prediction.diagnostics.evaluated,2);
  assert.ok(Math.abs(result.components.prediction.diagnostics.brier_score-.29)<1e-9);
  for(const component of Object.values(result.components)) assert.equal(component.score,null);
  assert.ok(!result.interpretation.includes('genuine learning'));
});
test('an empty or partially observed long window cannot satisfy anti-decay', () => {
  assert.equal(anti.isAntiDecaySatisfied({long:{has_baseline:true,crm_delta:null}}).satisfied,false);
  assert.equal(anti.isAntiDecaySatisfied({long:{has_baseline:true,crm_delta:0,component_deltas:{}}}).satisfied,false);
  const components=Object.fromEntries(crm.COMPONENTS.map(k=>[k,{delta:0}]));
  assert.equal(anti.isAntiDecaySatisfied({long:{has_baseline:true,crm_delta:0,component_deltas:components}}).satisfied,true);
});

test('new unknown benchmarks retain same-day legacy rows instead of overwriting history', async () => {
  const { runBenchmark } = await import('../evaluation/benchmark-harness.js');
  await pool.query(`INSERT INTO benchmark_history (benchmark_date,composite,run_source,evaluation_version)
    VALUES (CURRENT_DATE,.7,'fixture','activity-v1')`);
  const run = await runBenchmark({runSource:'fixture'});
  assert.equal(run.stored,true); assert.equal(run.benchmark.composite,null);
  assert.equal(run.benchmark.evaluation_version,'behavioral-v2');
  assert.equal((await pool.query("SELECT composite FROM benchmark_history WHERE evaluation_version='activity-v1'")).rows[0].composite,.7);
  assert.equal((await runBenchmark({runSource:'fixture'})).skipped,true);
});
test('causal completion needs actual execution plus supplied observation evidence, never an invented score', async () => {
  const c = await import('../causal/engine.js');
  const e = await c.designExperiment({causeDescription:'fixture',intervention:'measure fixture'});
  await assert.rejects(c.completeExperiment(e.id,{actualOutcome:'seems done'}),/outcomeEvidence/);
  const evidence={outcomeEvidence:[{id:'measurement',source:'fixture probe',observation:'result is 2'}]};
  assert.equal(await c.completeExperiment(e.id,{actualOutcome:'result is 2',metadata:evidence}),null,'unstarted experiment cannot complete');
  await c.startExperiment(e.id);
  await assert.rejects(c.completeExperiment(e.id,{actualOutcome:'result is 2',causalSupport:.8,metadata:evidence}),/verified comparison/);
  const done=await c.completeExperiment(e.id,{actualOutcome:'result is 2',metadata:evidence});
  assert.equal(done.status,'completed'); assert.equal(done.causal_support,null);
  assert.equal(await c.startExperiment(e.id),null,'closed experiment cannot resurrect');
  const abandoned=await c.designExperiment({causeDescription:'fixture',intervention:'never executed'});
  const expired=await c.completeExperiment(abandoned.id,{status:'abandoned',actualOutcome:'timed out'});
  assert.equal(expired.causal_support,null); assert.equal(expired.outcome_valence,null);
});
test('counterfactual accuracy stays unknown when only the original outcome is supplied', async () => {
  const s = await import('../simulation/engine.js');
  const cf=(await pool.query(`INSERT INTO counterfactuals (actual_action,alternative_action,predicted_alternative_outcome)
    VALUES ('original','alternative','result would differ') RETURNING id`)).rows[0];
  const r=await s.evaluateCounterfactual(cf.id,'result would differ');
  assert.equal(r.accuracy,null); assert.equal(r.status,'needs_intervention_evidence');
  assert.equal((await pool.query('SELECT accuracy_score FROM counterfactuals WHERE id=$1',[cf.id])).rows[0].accuracy_score,null);
});

test('user completion requires an existing active intention and preserves its first completion receipt', async () => {
  const prospective = await import('../memory/prospective.js');
  await assert.rejects(prospective.complete(-1), /Valid intention/);
  await assert.rejects(prospective.complete(2147483647), /not found/);
  const pending = await prospective.intend('Isolated UI completion test', 'time', {at:'2099-01-01T00:00:00Z'});
  const first = await prospective.complete(pending.id);
  const again = await prospective.complete(pending.id);
  assert.equal(first.status, 'completed');
  assert.deepEqual(first.completed_at, again.completed_at);
  const cancelled = await prospective.intend('Isolated cancelled test', 'time', {at:'2099-01-01T00:00:00Z'});
  await prospective.cancel(cancelled.id);
  await assert.rejects(prospective.complete(cancelled.id), /no longer active/);
});

test('user experiment tools record a real lifecycle and attributed evidence, never an unstarted success', async () => {
  const { createUserOperations } = await import('../user-operations.js');
  const causal = await import('../causal/engine.js');
  const operations = createUserOperations({layers:{causal}}, {});
  const designed = await operations.experiment({causeDescription:'Isolated test: would a warmer cache reduce latency?', intervention:'Perform the cache run in a private fixture', expectedEffect:'Measured latency is lower'});
  const input = {experimentId:designed.id, actualOutcome:'Fixture measured 12ms', source:'Isolated fixture test', observation:'The local controlled fixture recorded 12ms'};
  await assert.rejects(operations.experimentOutcome(input), /began this experiment/);
  const started = await operations.experimentStarted({experimentId:designed.id});
  assert.equal(started.status, 'running');
  const complete = await operations.experimentOutcome(input);
  assert.equal(complete.status, 'completed');
  assert.equal(complete.causal_support, null, 'no numeric causal credit from a reported outcome');
  assert.equal(complete.metadata.outcomeEvidence[0].source, input.source);
  await assert.rejects(operations.experimentOutcome(input), /cannot accept results/);
});
