#!/usr/bin/env python3
"""
Train Phase 7 Design Head — completes Phase 7 + Phase 8 properly.

What v6 shipped (correctly): heteroscedastic uncertainty (Phase 6),
LoRA-on-pooled-features (Phase 7-lite), and Bradley-Terry preference
training on the 23 flywheel pairs (Phase 8-lite).

What v6 *didn't* finish:
  - Phase 7 was a soft adapter on the *pooled* 1280-d features, which
    can only re-mix what AdaptiveAvgPool2d already squashed.  ImageNet
    bias lives in the spatial conv layers, so a real partial unfreeze
    fine-tunes the conv that produces those features.
  - Phase 8 only used 23 paired comparisons.  We have 452 manifest
    samples with overall_aesthetic scores — synthesizing pairs from
    score margins gives orders of magnitude more BT signal.

v7 finishes both:
  Phase 7 (real)  Make features[18] trainable in MLX.  features[18] is
                   the final 1×1 conv (320→1280) + BN + ReLU6 that
                   produces MobileNet's image-level representation.  It's
                   ~414K params and is exactly where ImageNet bias is
                   strongest.  Loaded from mobilenet_v2_imagenet.safetensors,
                   trained at 1/10× the head LR to avoid destroying it.
  Phase 8 (real)  Synthesize ≤2000 preference pairs from manifest pairs
                   where |overall_aesthetic margin| > threshold.  Per-dim
                   winner weighted by per-dim margin.  Combined with the
                   23 real flywheel pairs at training time.

Caches
  data/mobilenet_pre_features.npz   (452, 7, 7, 320) PyTorch features[0..17]
                                     output, generated by
                                     extract_features.py --include-pre

Outputs
  weights/design-head-v7.safetensors   — head + v7-trained features[18]
  weights/train-v7-meta.json
"""

import argparse
import json
import math
import re
import time
from pathlib import Path

import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim
from mlx.utils import tree_flatten, tree_map, tree_unflatten
import numpy as np


DATA_DIR = Path(__file__).parent.parent / "data"
WEIGHTS_DIR = Path(__file__).parent.parent / "weights"
MANIFEST_PATH = DATA_DIR / "manifest.json"
COMPARISONS_PATH = DATA_DIR / "comparisons.json"
CRITIQUE_EMBEDDINGS_PATH = DATA_DIR / "critique_embeddings.npz"
PRE_FEATURES_PATH = DATA_DIR / "mobilenet_pre_features.npz"

V6_WEIGHTS_PATH = WEIGHTS_DIR / "design-head-v6.safetensors"
V7_WEIGHTS_PATH = WEIGHTS_DIR / "design-head-v7.safetensors"
MOBILENET_WEIGHTS_PATH = WEIGHTS_DIR / "mobilenet_v2_imagenet.safetensors"

OUTPUT_DIM = 16
CRITIQUE_DIM = 3072
MIN_AUX_SAMPLES = 20

DEFAULT_AUX_WEIGHT = 0.1
DEFAULT_PREF_WEIGHT = 0.2
DEFAULT_NLL_WEIGHT = 1.0
DEFAULT_BACKBONE_LR_RATIO = 0.1   # backbone trains at 10% of head LR
DEFAULT_PAIR_MARGIN = 0.10
DEFAULT_PAIR_DIM_MARGIN = 0.05
DEFAULT_MAX_SYNTH_PAIRS = 2000
DEFAULT_ADAPTER_RANK = 64
DEFAULT_ADAPTER_ALPHA = 0.05

SCORE_NAMES = [
    "typography_quality", "color_harmony", "spatial_composition",
    "motion_elegance", "emotional_resonance", "craft_visibility",
    "minimalism_coherence", "native_integration",
    "visceral_score", "behavioral_score", "reflective_score",
    "overall_aesthetic",
    "innovation_score", "system_creativity", "design_distinctiveness",
    "problem_level",
]

DIMENSION_WEIGHTS = mx.array([
    1.2, 1.1, 1.1, 0.9, 1.3, 1.2, 1.0, 1.0,
    1.2, 1.0, 1.1, 1.5,
    1.4, 1.3, 1.2, 1.1,
], dtype=mx.float32)


# ═══════════════════════════════════════════════════
# MOBILENET FEATURES[18] — TRAINABLE 1×1 CONV + BN + ReLU6
# ═══════════════════════════════════════════════════


class MobileNetHeadConv(nn.Module):
    """The MobileNet V2 final block: 1×1 conv (320→1280) + BN + ReLU6, with
    the BatchNorm folded into the conv weights at init.

    BN folding (a.k.a. fused-BN) bakes the affine BN transformation
    γ·(x − μ)/√(σ² + ε) + β into the preceding convolution.  After folding:

        fused_w[c, ...] = conv_w[c, ...] * γ[c] / √(σ²[c] + ε)
        fused_b[c]      = β[c] − μ[c] * γ[c] / √(σ²[c] + ε)

    The forward pass collapses to: clip(conv_with_bias(x), 0, 6) → pool.
    Training has only ONE parameter set (the fused conv), no BN state to
    corrupt under weight_decay.  This is the same trick production
    inference pipelines use.

    Forward expects NHWC: (B, 7, 7, 320) → (B, 7, 7, 1280) → pool → (B, 1280).
    """

    def __init__(self):
        super().__init__()
        # 1×1 conv with bias enabled (so the folded β can live there).
        self.conv = nn.Conv2d(in_channels=320, out_channels=1280,
                              kernel_size=1, bias=True)

    def load_imagenet_weights(self, mobilenet_path: Path):
        """Load MobileNet's features[18] and fold its BN into the conv."""
        if not mobilenet_path.exists():
            raise FileNotFoundError(f"missing {mobilenet_path}")
        w = mx.load(str(mobilenet_path))

        conv_w = w["features.18.0.weight"]            # (1280, 1, 1, 320)
        bn_g = w["features.18.1.weight"]              # γ — BN scale
        bn_b = w["features.18.1.bias"]                # β — BN shift
        bn_m = w["features.18.1.running_mean"]        # μ
        bn_v = w["features.18.1.running_var"]         # σ²
        eps = 1e-5

        scale = bn_g / mx.sqrt(bn_v + eps)            # (1280,)
        # Broadcast scale into the (1280, 1, 1, 320) weight: same scale per
        # output channel, applied to all spatial+input dims.
        fused_w = conv_w * scale.reshape(1280, 1, 1, 1)
        fused_b = bn_b - bn_m * scale                 # (1280,)

        self.conv.weight = fused_w
        self.conv.bias = fused_b

    def __call__(self, x):
        # x: (B, 7, 7, 320)
        x = self.conv(x)                       # (B, 7, 7, 1280)
        x = mx.clip(x, 0.0, 6.0)               # ReLU6
        x = mx.mean(x, axis=(1, 2))            # AdaptiveAvgPool2d((1,1))
        return x


# ═══════════════════════════════════════════════════
# DESIGN HEAD V7 — v6 architecture + trainable backbone tail
# ═══════════════════════════════════════════════════


class FeatureAdapter(nn.Module):
    def __init__(self, dim: int = 1280, rank: int = DEFAULT_ADAPTER_RANK,
                 init_alpha: float = DEFAULT_ADAPTER_ALPHA):
        super().__init__()
        self.up = nn.Linear(dim, rank)
        self.down = nn.Linear(rank, dim)
        self.alpha = mx.array(init_alpha, dtype=mx.float32)

    def __call__(self, x):
        return x + self.alpha * self.down(nn.gelu(self.up(x)))


class DesignHeadV7(nn.Module):
    """v6 trunk + Phase 6 (uncertainty) + Phase 7 (LoRA + features[18]) + Phase 8 (pref).

    Forward modes:
      visual_features = pre-pool (B, 7, 7, 320):
        runs MobileNet features[18] (trainable) → pool → 1280 → adapter → trunk → heads
      visual_features = pooled (B, 1280):
        legacy v6-style path; backbone stays frozen since features[18]
        wasn't applied at training time.  Use at inference when the caller
        only has pooled features.
    """

    def __init__(self, dropout: float = 0.5,
                 critique_dim: int = CRITIQUE_DIM,
                 adapter_rank: int = DEFAULT_ADAPTER_RANK,
                 adapter_alpha: float = DEFAULT_ADAPTER_ALPHA,
                 enable_adapter: bool = True,
                 enable_backbone: bool = True):
        super().__init__()

        self.enable_adapter = enable_adapter
        self.enable_backbone = enable_backbone

        if enable_backbone:
            self.backbone = MobileNetHeadConv()

        if enable_adapter:
            self.adapter = FeatureAdapter(1280, adapter_rank, adapter_alpha)

        # ── v6 trunk (warm-startable) ──
        self.vis_proj = nn.Linear(1280, 384)
        self.vis_norm = nn.LayerNorm(384)
        self.code_proj = nn.Linear(64, 128)
        self.code_norm = nn.LayerNorm(128)

        self.fc1 = nn.Linear(384 + 128, 256)
        self.ln1 = nn.LayerNorm(256)
        self.drop1 = nn.Dropout(dropout)

        self.fc2 = nn.Linear(256, 128)
        self.ln2 = nn.LayerNorm(128)
        self.drop2 = nn.Dropout(dropout * 0.8)

        self.fc3 = nn.Linear(128, 64)
        self.ln3 = nn.LayerNorm(64)
        self.drop3 = nn.Dropout(dropout * 0.6)

        self.output = nn.Linear(64, OUTPUT_DIM)
        self.log_var = nn.Linear(64, OUTPUT_DIM)

        # Critique aux head (Phase 5, dormant unless data plumbed)
        self.aux_fc1 = nn.Linear(64, 256)
        self.aux_fc2 = nn.Linear(256, 512)
        self.aux_out = nn.Linear(512, critique_dim)

        # Preference head (Phase 8) — per-dim logits
        self.pref_head = nn.Linear(64, OUTPUT_DIM)

    def trunk(self, visual_features, code_features=None):
        """Run backbone (if 4D) + adapter + v6 trunk → 64-dim representation."""
        if visual_features.ndim == 4:
            if not self.enable_backbone:
                raise RuntimeError("Got pre-pool features but backbone is disabled")
            x = self.backbone(visual_features)  # (B, 1280)
        else:
            x = visual_features  # already pooled

        if self.enable_adapter and hasattr(self, "adapter"):
            x = self.adapter(x)

        v = self.drop1(nn.gelu(self.vis_norm(self.vis_proj(x))))

        if code_features is not None:
            c = nn.gelu(self.code_norm(self.code_proj(code_features)))
        else:
            c = mx.zeros((v.shape[0], 128))

        h = mx.concatenate([v, c], axis=-1)
        h = self.drop1(nn.gelu(self.ln1(self.fc1(h))))
        h = self.drop2(nn.gelu(self.ln2(self.fc2(h))))
        return self.drop3(nn.gelu(self.ln3(self.fc3(h))))

    def __call__(self, visual_features, code_features=None,
                 return_aux: bool = False, return_uncertainty: bool = False,
                 return_preference: bool = False):
        h64 = self.trunk(visual_features, code_features)
        scores = mx.sigmoid(self.output(h64))
        out = [scores]
        if return_uncertainty:
            out.append(self.log_var(h64))
        if return_aux:
            aux = nn.gelu(self.aux_fc1(h64))
            aux = nn.gelu(self.aux_fc2(aux))
            out.append(self.aux_out(aux))
        if return_preference:
            out.append(self.pref_head(h64))
        return out[0] if len(out) == 1 else tuple(out)

    def param_count(self):
        return sum(p.size for _, p in tree_flatten(self.parameters()))


def warm_start_from_v6(model: DesignHeadV7, v6_path: Path) -> bool:
    if not v6_path.exists():
        print(f"[v7] no v6 checkpoint at {v6_path} — trunk init random")
        return False
    try:
        model.load_weights(str(v6_path), strict=False)
        print(f"[v7] warm-started trunk + adapter from v6: {v6_path.name}")
        return True
    except Exception as e:
        print(f"[v7] WARNING: v6 warm-start failed ({e})")
        return False


# ═══════════════════════════════════════════════════
# CRITIQUE EMBEDDING LOOKUP (carried from v6)
# ═══════════════════════════════════════════════════


def load_critique_embeddings():
    if not CRITIQUE_EMBEDDINGS_PATH.exists():
        return {}
    try:
        with np.load(CRITIQUE_EMBEDDINGS_PATH) as npz:
            cycle_ids = npz["cycle_ids"].tolist()
            embeddings = npz["embeddings"]
            if len(cycle_ids) != embeddings.shape[0]:
                return {}
            return {int(cid): embeddings[i] for i, cid in enumerate(cycle_ids)}
    except Exception:
        return {}


_CYCLE_RE = re.compile(r"(?:self[-_]train[-_](\d+))|(?:cycle[-_]?(\d+))",
                       re.IGNORECASE)


def extract_cycle_id(s):
    if not s:
        return None
    m = _CYCLE_RE.search(str(s))
    if m:
        try:
            return int(m.group(1) or m.group(2))
        except (ValueError, TypeError):
            return None
    return None


# ═══════════════════════════════════════════════════
# DATASET — pre-pool features + score-based pair synthesis
# ═══════════════════════════════════════════════════


class FeatureDatasetV7:
    """Loads pre-pool features (NHWC) for all manifest samples that have them.

    Phase 8: synthesizes BT pairs from regression scores within the train
    split.  Falls back to flywheel comparisons.json when those exist (and
    deduplicates so synth pairs don't collide with real pairs).
    """

    def __init__(self, max_synth_pairs: int = DEFAULT_MAX_SYNTH_PAIRS,
                 pair_overall_margin: float = DEFAULT_PAIR_MARGIN,
                 pair_dim_margin: float = DEFAULT_PAIR_DIM_MARGIN):

        # ── Load pre-features sidecar ──
        if not PRE_FEATURES_PATH.exists():
            raise FileNotFoundError(
                f"No pre-pool features at {PRE_FEATURES_PATH}. "
                f"Run `python extract_features.py --include-pre` first."
            )
        with np.load(PRE_FEATURES_PATH) as npz:
            self.pre_indices = npz["indices"].astype(np.int64)
            self.pre_features = npz["features"].astype(np.float32)
        idx_to_pre = {int(i): k for k, i in enumerate(self.pre_indices.tolist())}

        # ── Load manifest and align ──
        with open(MANIFEST_PATH) as f:
            manifest = json.load(f)
        self.critique_by_cycle = load_critique_embeddings()

        self.pre_idx_in_dataset = []  # which row in self.pre_features
        self.targets = []
        self.code_features = []
        self.critique_embeddings = []
        self.critique_mask = []
        self.names = []
        self.manifest_indices = []   # original manifest index for joining pairs

        # Path → row in this dataset, used for flywheel pair joining
        self.path_to_idx = {}

        matched = 0
        for mi, sample in enumerate(manifest["samples"]):
            if mi not in idx_to_pre:
                continue
            scores = sample.get("scores", {})
            target = [float(scores.get(n, 0.5)) for n in SCORE_NAMES]

            row = len(self.pre_idx_in_dataset)
            self.pre_idx_in_dataset.append(idx_to_pre[mi])
            self.targets.append(target)
            self.manifest_indices.append(mi)

            code = sample.get("code_features")
            self.code_features.append(code if code and len(code) == 64 else [0.0] * 64)

            meta = sample.get("metadata", {})
            cycle_id = extract_cycle_id(meta.get("source_name", ""))
            if cycle_id is None:
                cycle_id = extract_cycle_id(meta.get("code_path", ""))
            if cycle_id is not None and cycle_id in self.critique_by_cycle:
                self.critique_embeddings.append(self.critique_by_cycle[cycle_id].tolist())
                self.critique_mask.append(1.0)
                matched += 1
            else:
                self.critique_embeddings.append([0.0] * CRITIQUE_DIM)
                self.critique_mask.append(0.0)

            self.names.append(meta.get("source_name") or meta.get("category", "unknown"))

            for k in ("image", "screenshot_path"):
                p = sample.get(k)
                if p:
                    self.path_to_idx[p] = row

        self.n_matched = matched
        self.n_samples = len(self.pre_idx_in_dataset)

        # ── Real flywheel pairs ──
        self.real_pairs = []
        if COMPARISONS_PATH.exists():
            comps = json.loads(COMPARISONS_PATH.read_text())
            for pair in comps.get("pairs", []):
                ia = self.path_to_idx.get(pair.get("image_a"))
                ib = self.path_to_idx.get(pair.get("image_b"))
                if ia is None or ib is None:
                    continue
                winner = np.zeros(OUTPUT_DIM, dtype=np.float32)
                margin = np.zeros(OUTPUT_DIM, dtype=np.float32)
                prefs = pair.get("preferences", {})
                for d, name in enumerate(SCORE_NAMES):
                    p = prefs.get(name, {})
                    w = p.get("winner")
                    winner[d] = 1.0 if w == "A" else -1.0 if w == "B" else 0.0
                    margin[d] = float(p.get("margin", 0.0))
                self.real_pairs.append((ia, ib, winner, margin))

        # Synthesized pairs are filled in after split() because we want to
        # restrict synthesis to the train split.
        self.synth_pairs = []
        self.pair_overall_margin = pair_overall_margin
        self.pair_dim_margin = pair_dim_margin
        self.max_synth_pairs = max_synth_pairs

    def __len__(self):
        return self.n_samples

    def split(self, val_ratio=0.15, seed=42):
        rng = np.random.default_rng(seed)
        n = self.n_samples
        indices = np.arange(n)
        rng.shuffle(indices)
        n_val = max(2, int(n * val_ratio))
        val_idx = set(indices[:n_val].tolist())
        train_idx = [i for i in range(n) if i not in val_idx]
        val_idx = list(val_idx)

        # Synthesize pairs over the train split only — leak-free
        self.synth_pairs = self._synthesize_pairs(train_idx, rng)
        return train_idx, val_idx

    def _synthesize_pairs(self, train_idx, rng):
        """Build BT pairs from train-split samples whose overall margins exceed
        threshold.  Per-dim winners are derived from per-dim margins."""
        targets = np.asarray(self.targets, dtype=np.float32)
        overall_idx = SCORE_NAMES.index("overall_aesthetic")

        candidates = []  # (i, j, overall_margin)
        train_set = list(train_idx)
        # Reservoir-style: enumerate pairs but cap the search.
        # 385 train samples → 73,920 unordered pairs.  Sample a random subset
        # of pairs to consider for tractability, then filter by margin.
        max_to_examine = min(50_000, len(train_set) * (len(train_set) - 1) // 2)
        examined = 0
        for i in range(len(train_set)):
            for j in range(i + 1, len(train_set)):
                if examined >= max_to_examine:
                    break
                examined += 1
                a, b = train_set[i], train_set[j]
                m = abs(targets[a, overall_idx] - targets[b, overall_idx])
                if m > self.pair_overall_margin:
                    candidates.append((a, b, m))

        if not candidates:
            return []

        # Sample uniformly to cap (preserves diversity better than top-k by margin)
        if len(candidates) > self.max_synth_pairs:
            picks = rng.choice(len(candidates), self.max_synth_pairs, replace=False)
            candidates = [candidates[k] for k in picks]

        pairs = []
        for a, b, _m in candidates:
            winner = np.zeros(OUTPUT_DIM, dtype=np.float32)
            margin = np.zeros(OUTPUT_DIM, dtype=np.float32)
            for d in range(OUTPUT_DIM):
                ma = float(targets[a, d])
                mb = float(targets[b, d])
                diff = ma - mb
                if abs(diff) > self.pair_dim_margin:
                    winner[d] = 1.0 if diff > 0 else -1.0
                    margin[d] = abs(diff)
            pairs.append((a, b, winner, margin))
        return pairs

    @property
    def all_pairs(self):
        return self.real_pairs + self.synth_pairs

    def get_regression_batch(self, indices):
        feats = mx.array(self.pre_features[[self.pre_idx_in_dataset[i] for i in indices]])
        targets = mx.array(np.array([self.targets[i] for i in indices], dtype=np.float32))
        codes = mx.array(np.array([self.code_features[i] for i in indices], dtype=np.float32))
        crits = mx.array(np.array([self.critique_embeddings[i] for i in indices], dtype=np.float32))
        mask = mx.array(np.array([self.critique_mask[i] for i in indices], dtype=np.float32))
        return feats, targets, codes, crits, mask

    def get_preference_batch(self, indices):
        if not indices:
            empty4 = mx.zeros((0, 7, 7, 320))
            return empty4, empty4, mx.zeros((0, 64)), mx.zeros((0, 64)), \
                   mx.zeros((0, OUTPUT_DIM)), mx.zeros((0, OUTPUT_DIM))

        pairs = self.all_pairs
        feat_a, feat_b, code_a, code_b, win, marg = [], [], [], [], [], []
        for k in indices:
            a, b, w, m = pairs[k]
            feat_a.append(self.pre_features[self.pre_idx_in_dataset[a]])
            feat_b.append(self.pre_features[self.pre_idx_in_dataset[b]])
            code_a.append(self.code_features[a])
            code_b.append(self.code_features[b])
            win.append(w)
            marg.append(m)

        return (mx.array(np.stack(feat_a, dtype=np.float32)),
                mx.array(np.stack(feat_b, dtype=np.float32)),
                mx.array(np.stack(code_a, dtype=np.float32).astype(np.float32)),
                mx.array(np.stack(code_b, dtype=np.float32).astype(np.float32)),
                mx.array(np.stack(win, dtype=np.float32).astype(np.float32)),
                mx.array(np.stack(marg, dtype=np.float32).astype(np.float32)))


# ═══════════════════════════════════════════════════
# LOSSES (carried from v6)
# ═══════════════════════════════════════════════════


def gaussian_nll_loss(predictions, log_var, targets):
    log_var = mx.clip(log_var, -7.0, 4.0)
    inv_var = mx.exp(-log_var)
    diff = predictions - targets
    nll = 0.5 * (inv_var * diff * diff + log_var) * DIMENSION_WEIGHTS
    main = mx.mean(nll)

    overall_idx = SCORE_NAMES.index("overall_aesthetic")
    pred_overall = predictions[:, overall_idx]
    part_indices = [i for i, n in enumerate(SCORE_NAMES)
                    if n not in ("overall_aesthetic", "innovation_score",
                                 "system_creativity", "design_distinctiveness",
                                 "problem_level")]
    pred_parts_mean = mx.mean(predictions[:, part_indices], axis=1)
    incoherence = mx.maximum(pred_parts_mean - pred_overall - 0.05, 0)
    coherence = mx.mean(incoherence * incoherence) * 2.0
    return main + coherence


def weighted_mse_loss(predictions, targets):
    diff = predictions - targets
    loss = diff * diff * DIMENSION_WEIGHTS
    mse = mx.mean(loss)
    overall_idx = SCORE_NAMES.index("overall_aesthetic")
    pred_overall = predictions[:, overall_idx]
    part_indices = [i for i, n in enumerate(SCORE_NAMES)
                    if n not in ("overall_aesthetic", "innovation_score",
                                 "system_creativity", "design_distinctiveness",
                                 "problem_level")]
    pred_parts_mean = mx.mean(predictions[:, part_indices], axis=1)
    incoherence = mx.maximum(pred_parts_mean - pred_overall - 0.05, 0)
    coherence_penalty = mx.mean(incoherence * incoherence) * 2.0
    return mse + coherence_penalty


def cosine_distance_masked(pred_emb, target_emb, mask):
    pred_norm = pred_emb / (mx.linalg.norm(pred_emb, axis=-1, keepdims=True) + 1e-8)
    target_norm = target_emb / (mx.linalg.norm(target_emb, axis=-1, keepdims=True) + 1e-8)
    cos_sim = mx.sum(pred_norm * target_norm, axis=-1)
    distance = 1.0 - cos_sim
    masked = distance * mask
    denom = mx.maximum(mx.sum(mask), mx.array(1.0))
    return mx.sum(masked) / denom


def bradley_terry_loss(pref_a, pref_b, winner, margin):
    abs_winner = mx.abs(winner)
    target_diff = winner * (pref_a - pref_b)
    softplus_neg = mx.logaddexp(mx.zeros_like(target_diff), -target_diff)
    per_elem = softplus_neg * abs_winner * margin
    denom = mx.maximum(mx.sum(abs_winner * margin), mx.array(1.0))
    return mx.sum(per_elem) / denom


# ═══════════════════════════════════════════════════
# TRAINING
# ═══════════════════════════════════════════════════


def train(epochs=200, batch_size=16, learning_rate=1e-3,
          backbone_lr_ratio=DEFAULT_BACKBONE_LR_RATIO,
          weight_decay=0.05, warmup_steps=20, patience=30, dropout=0.5,
          aux_weight=DEFAULT_AUX_WEIGHT, pref_weight=DEFAULT_PREF_WEIGHT,
          nll_weight=DEFAULT_NLL_WEIGHT,
          adapter_rank=DEFAULT_ADAPTER_RANK,
          adapter_alpha=DEFAULT_ADAPTER_ALPHA,
          max_synth_pairs=DEFAULT_MAX_SYNTH_PAIRS,
          pair_overall_margin=DEFAULT_PAIR_MARGIN,
          pair_dim_margin=DEFAULT_PAIR_DIM_MARGIN,
          disable_aux=False, disable_adapter=False, disable_pref=False,
          disable_backbone=False, from_scratch=False):

    print("[v7] loading dataset...")
    dataset = FeatureDatasetV7(
        max_synth_pairs=max_synth_pairs,
        pair_overall_margin=pair_overall_margin,
        pair_dim_margin=pair_dim_margin,
    )
    print(f"[v7] {len(dataset)} samples (with pre-pool features)")
    print(f"[v7] critique embeddings matched: {dataset.n_matched}")

    train_idx, val_idx = dataset.split()
    print(f"[v7] split: {len(train_idx)} train, {len(val_idx)} val")
    print(f"[v7] pairs: {len(dataset.real_pairs)} real (flywheel) + "
          f"{len(dataset.synth_pairs)} synthetic (margin>{pair_overall_margin}) = "
          f"{len(dataset.all_pairs)} total")

    aux_enabled = (not disable_aux) and (dataset.n_matched >= MIN_AUX_SAMPLES)
    pref_enabled = (not disable_pref) and (len(dataset.all_pairs) >= 5)
    adapter_enabled = not disable_adapter
    backbone_enabled = not disable_backbone

    print(f"[v7] phases: "
          f"backbone={'on (trainable)' if backbone_enabled else 'off'} "
          f"adapter={'on' if adapter_enabled else 'off'} "
          f"uncertainty=on "
          f"pref={'on' if pref_enabled else 'off'} "
          f"aux={'on' if aux_enabled else 'off'}")

    model = DesignHeadV7(
        dropout=dropout,
        adapter_rank=adapter_rank,
        adapter_alpha=adapter_alpha,
        enable_adapter=adapter_enabled,
        enable_backbone=backbone_enabled,
    )
    if not from_scratch:
        warm_start_from_v6(model, V6_WEIGHTS_PATH)
    if backbone_enabled:
        model.backbone.load_imagenet_weights(MOBILENET_WEIGHTS_PATH)
        print(f"[v7] backbone features[18] loaded from {MOBILENET_WEIGHTS_PATH.name}")
    print(f"[v7] head: {model.param_count():,} params")

    # Per-parameter learning rate: backbone gets backbone_lr_ratio × head LR.
    # MLX optimizers don't natively support param groups, so we scale grads
    # of backbone params by the ratio inside the training loop.
    backbone_param_paths = (
        {f"backbone.{k}" for k, _ in tree_flatten(model.backbone.parameters())}
        if backbone_enabled else set()
    )

    optimizer = optim.AdamW(learning_rate=learning_rate, weight_decay=weight_decay)
    steps_per_epoch = max(1, len(train_idx) // batch_size)
    total_steps = epochs * steps_per_epoch

    def loss_fn(model, feats, targets, codes, crits, mask,
                feat_a, feat_b, code_a, code_b, winner, margin):
        scores, log_var, critique_preds, _pref = model(
            feats, codes,
            return_aux=True, return_uncertainty=True, return_preference=True,
        )
        nll = gaussian_nll_loss(scores, log_var, targets)
        total = nll_weight * nll

        if aux_enabled:
            aux = cosine_distance_masked(critique_preds, crits, mask)
            total = total + aux_weight * aux

        if pref_enabled and feat_a.shape[0] > 0:
            pref_a = model(feat_a, code_a, return_preference=True)[1]
            pref_b = model(feat_b, code_b, return_preference=True)[1]
            bt = bradley_terry_loss(pref_a, pref_b, winner, margin)
            total = total + pref_weight * bt

        return total

    loss_and_grad = nn.value_and_grad(model, loss_fn)

    best_val_loss = float("inf")
    patience_counter = 0
    global_step = 0
    best_per_dim = None
    best_uncertainty = None

    print(f"[v7] training: {epochs} epochs, batch {batch_size}, head_lr {learning_rate}, "
          f"backbone_lr {learning_rate * backbone_lr_ratio:.2e}")
    print(f"[v7] regularization: dropout={dropout}, weight_decay={weight_decay}")
    print()

    pref_rng = np.random.default_rng(0)

    for epoch in range(epochs):
        model.train()
        if backbone_enabled:
            model.backbone.eval()  # Keep BN in eval mode for the backbone

        t0 = time.time()
        rng = np.random.default_rng(epoch)
        shuffled = rng.permutation(train_idx).tolist()

        epoch_loss = 0.0
        epoch_steps = 0

        for start in range(0, len(shuffled), batch_size):
            batch_idx = shuffled[start:start + batch_size]
            feats, targets, codes, crits, mask = dataset.get_regression_batch(batch_idx)

            if pref_enabled and dataset.all_pairs:
                pref_batch_size = max(4, batch_size // 2)
                pref_idx = pref_rng.integers(
                    0, len(dataset.all_pairs),
                    size=min(pref_batch_size, len(dataset.all_pairs)),
                ).tolist()
            else:
                pref_idx = []
            feat_a, feat_b, code_a, code_b, winner, margin = \
                dataset.get_preference_batch(pref_idx)

            if global_step < warmup_steps:
                lr = learning_rate * global_step / max(warmup_steps, 1)
            else:
                progress = (global_step - warmup_steps) / max(total_steps - warmup_steps, 1)
                lr = 1e-6 + 0.5 * (learning_rate - 1e-6) * (1 + math.cos(math.pi * progress))
            optimizer.learning_rate = lr

            loss, grads = loss_and_grad(
                model, feats, targets, codes, crits, mask,
                feat_a, feat_b, code_a, code_b, winner, margin,
            )

            # Scale backbone gradients down so the conv adapts gently.
            if backbone_param_paths:
                grad_flat = tree_flatten(grads)
                scaled = []
                for path, g in grad_flat:
                    if path in backbone_param_paths:
                        scaled.append((path, g * backbone_lr_ratio))
                    else:
                        scaled.append((path, g))
                grads = tree_unflatten(scaled)

            grad_flat = tree_flatten(grads)
            grad_norm = mx.sqrt(sum(mx.sum(g * g) for _, g in grad_flat))
            if grad_norm > 1.0:
                scale = 1.0 / (grad_norm + 1e-8)
                grads = tree_map(lambda g: g * scale, grads)

            optimizer.update(model, grads)
            mx.eval(model.parameters(), optimizer.state, loss)

            epoch_loss += float(loss)
            epoch_steps += 1
            global_step += 1

        avg_train = epoch_loss / max(epoch_steps, 1)

        # Validation (on val split, regression only)
        model.eval()
        val_feats, val_targets, val_codes, _vc, _vm = dataset.get_regression_batch(val_idx)
        val_preds, val_log_var = model(val_feats, val_codes, return_uncertainty=True)
        val_loss = weighted_mse_loss(val_preds, val_targets)
        mx.eval(val_loss, val_preds, val_log_var)
        val_loss = float(val_loss)

        diff = mx.abs(val_preds - val_targets)
        mx.eval(diff)
        per_dim = [float(mx.mean(diff[:, i])) for i in range(OUTPUT_DIM)]

        std_per_dim = mx.sqrt(mx.exp(mx.clip(val_log_var, -7.0, 4.0)))
        mx.eval(std_per_dim)
        std_per_dim_list = [float(mx.mean(std_per_dim[:, i])) for i in range(OUTPUT_DIM)]

        elapsed = time.time() - t0

        if (epoch + 1) % 10 == 0 or val_loss < best_val_loss:
            print(f"  epoch {epoch + 1:4d}/{epochs} | "
                  f"train {avg_train:.4f} | val {val_loss:.4f} | "
                  f"lr {lr:.2e} | {elapsed:.2f}s")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0
            best_per_dim = per_dim
            best_uncertainty = std_per_dim_list

            WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)
            model.save_weights(str(V7_WEIGHTS_PATH))

            dim_str = " | ".join(f"{SCORE_NAMES[i][:6]}={per_dim[i]:.3f}"
                                 for i in range(OUTPUT_DIM))
            print(f"  >>> best: {dim_str}")
        else:
            patience_counter += 1

        if patience_counter >= patience:
            print(f"\n[v7] early stopping at epoch {epoch + 1}")
            break

    print(f"\n[v7] training complete!")
    print(f"[v7] best val loss: {best_val_loss:.4f}")

    if best_per_dim:
        print(f"\n[v7] per-dim MAE | predicted std:")
        for i, name in enumerate(SCORE_NAMES):
            mae = best_per_dim[i]
            std = best_uncertainty[i] if best_uncertainty else 0.0
            bar = "█" * int(mae * 50)
            print(f"  {name:25s}: {mae:.4f}  σ={std:.3f}  {bar}")

    meta = {
        "best_val_loss": best_val_loss,
        "epochs": epoch + 1,
        "per_dim_mae": {n: best_per_dim[i] for i, n in enumerate(SCORE_NAMES)} if best_per_dim else {},
        "per_dim_predicted_std": {n: best_uncertainty[i] for i, n in enumerate(SCORE_NAMES)} if best_uncertainty else {},
        "param_count": model.param_count(),
        "backbone": "mobilenet_v2_imagenet (features[18] trainable)" if backbone_enabled else "frozen",
        "feature_dim": 1280,
        "phases": {
            "phase_5_aux": {
                "enabled": aux_enabled,
                "weight": aux_weight if aux_enabled else 0.0,
                "samples_matched": dataset.n_matched,
            },
            "phase_6_uncertainty": {
                "enabled": True,
                "loss": "gaussian_nll",
                "weight": nll_weight,
            },
            "phase_7_adapter": {
                "enabled": adapter_enabled,
                "rank": adapter_rank if adapter_enabled else None,
            },
            "phase_7_backbone": {
                "enabled": backbone_enabled,
                "trainable_block": "features[18] (1×1 320→1280 conv + BN + ReLU6)",
                "lr_ratio": backbone_lr_ratio if backbone_enabled else 0.0,
            },
            "phase_8_preference": {
                "enabled": pref_enabled,
                "weight": pref_weight if pref_enabled else 0.0,
                "real_pairs": len(dataset.real_pairs),
                "synth_pairs": len(dataset.synth_pairs),
                "synth_overall_margin": pair_overall_margin,
                "synth_dim_margin": pair_dim_margin,
                "max_synth_pairs": max_synth_pairs,
            },
        },
        "warm_start_from_v6": (not from_scratch) and V6_WEIGHTS_PATH.exists(),
    }
    with open(WEIGHTS_DIR / "train-v7-meta.json", "w") as f:
        json.dump(meta, f, indent=2)

    return meta


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Phase 7 design head")
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--backbone-lr-ratio", type=float,
                        default=DEFAULT_BACKBONE_LR_RATIO)
    parser.add_argument("--weight-decay", type=float, default=0.05)
    parser.add_argument("--warmup", type=int, default=20)
    parser.add_argument("--patience", type=int, default=30)
    parser.add_argument("--dropout", type=float, default=0.5)
    parser.add_argument("--aux-weight", type=float, default=DEFAULT_AUX_WEIGHT)
    parser.add_argument("--pref-weight", type=float, default=DEFAULT_PREF_WEIGHT)
    parser.add_argument("--nll-weight", type=float, default=DEFAULT_NLL_WEIGHT)
    parser.add_argument("--max-synth-pairs", type=int, default=DEFAULT_MAX_SYNTH_PAIRS)
    parser.add_argument("--pair-overall-margin", type=float, default=DEFAULT_PAIR_MARGIN)
    parser.add_argument("--pair-dim-margin", type=float, default=DEFAULT_PAIR_DIM_MARGIN)
    parser.add_argument("--disable-aux", action="store_true")
    parser.add_argument("--disable-adapter", action="store_true")
    parser.add_argument("--disable-pref", action="store_true")
    parser.add_argument("--disable-backbone", action="store_true",
                        help="Skip Phase 7 backbone fine-tuning (v6-equivalent)")
    parser.add_argument("--from-scratch", action="store_true",
                        help="Skip v6 warm-start; train from random init")
    args = parser.parse_args()

    train(
        epochs=args.epochs,
        batch_size=args.batch,
        learning_rate=args.lr,
        backbone_lr_ratio=args.backbone_lr_ratio,
        weight_decay=args.weight_decay,
        warmup_steps=args.warmup,
        patience=args.patience,
        dropout=args.dropout,
        aux_weight=args.aux_weight,
        pref_weight=args.pref_weight,
        nll_weight=args.nll_weight,
        max_synth_pairs=args.max_synth_pairs,
        pair_overall_margin=args.pair_overall_margin,
        pair_dim_margin=args.pair_dim_margin,
        disable_aux=args.disable_aux,
        disable_adapter=args.disable_adapter,
        disable_pref=args.disable_pref,
        disable_backbone=args.disable_backbone,
        from_scratch=args.from_scratch,
    )
