name: OneiroApp
options:
  bundleIdPrefix: dev.upaway
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  OneiroApp:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.upaway.OneiroApp
        PRODUCT_NAME: Oneiro
        INFOPLIST_FILE: Sources/OneiroApp/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: H9DL9QRS26
        ENABLE_HARDENED_RUNTIME: "NO"
        OTHER_CODE_SIGN_FLAGS: "--deep"
    entitlements:
      path: Sources/OneiroApp/OneiroApp.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
    dependencies:
      - package: Alamofire
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    majorVersion: 5.8.0
